#!/usr/bin/env python3
"""Emit the LinearBase verdict for every Qwen3.5 GDN (linear-attention) module.

WS1 D3 / risk R3 resolution artifact. The loader must know which GDN parameters
are vLLM ``LinearBase`` instances (they pick up ``GGUFLinearMethod`` and load as
quantized weights) versus dense parameters (conv weight, dt bias, A_log, norms —
kept high-precision, dequant-on-load). This script derives that verdict
PROGRAMMATICALLY from the real vLLM classes constructed by
``QwenGatedDeltaNetAttention.__init__`` (vllm/model_executor/layers/mamba/gdn/
qwen_gdn_linear_attn.py) and writes docs/gdn-module-inventory.md.

Run (in the dev venv):
    python tools/introspect_gdn_modules.py --config tests/fixtures/qwen36_27b_metadata.json
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import torch.nn as nn
from vllm.model_executor.layers.layernorm import RMSNormGated
from vllm.model_executor.layers.linear import (
    ColumnParallelLinear,
    LinearBase,
    MergedColumnParallelLinear,
    RowParallelLinear,
)

# Authoritative param → constructed class map, read from
# QwenGatedDeltaNetAttention.__init__ (qwen_gdn_linear_attn.py, vLLM 0.25.0):
#   conv1d      = ColumnParallelLinear      (line ~467; causal conv modelled as a linear)
#   in_proj_qkvz= MergedColumnParallelLinear (create_qkvz_proj, line ~480)
#   in_proj_ba  = MergedColumnParallelLinear (create_ba_proj,  line ~491)
#   out_proj    = RowParallelLinear         (line ~545)
#   dt_bias     = nn.Parameter              (line ~516)
#   A_log       = nn.Parameter              (line ~519)
#   norm        = RMSNormGated              (line ~536)
GDN_MODULE_CLASSES: dict[str, type] = {
    "conv1d": ColumnParallelLinear,
    "in_proj_qkvz": MergedColumnParallelLinear,
    "in_proj_ba": MergedColumnParallelLinear,
    "out_proj": RowParallelLinear,
    "dt_bias": nn.Parameter,
    "A_log": nn.Parameter,
    "norm": RMSNormGated,
}

# Preliminary GGUF-tensor → vLLM-param correspondence for GDN blocks (grounds T-6;
# the split→merged projection mapping is T-6's to finalise).
GGUF_CORRESPONDENCE: dict[str, str] = {
    "ssm_conv1d.weight": "conv1d",
    "attn_qkv.weight + attn_gate.weight": "in_proj_qkvz (merged qkv + z gate)",
    "ssm_alpha.weight + ssm_beta.weight": "in_proj_ba (merged b + a)",
    "ssm_out.weight": "out_proj",
    "ssm_dt.bias": "dt_bias",
    "ssm_a": "A_log",
    "ssm_norm.weight": "norm",
}


def linearbase_verdict(cls: type) -> bool:
    return isinstance(cls, type) and issubclass(cls, LinearBase)


def build_doc(config_meta: dict | None) -> str:
    lines: list[str] = []
    lines.append("# Qwen3.5 GDN module inventory — LinearBase verdicts\n")
    lines.append(
        "Generated by `tools/introspect_gdn_modules.py` (WS1 D3 / R3). Verdicts are "
        "computed with `issubclass(cls, LinearBase)` against the real vLLM classes "
        "that `QwenGatedDeltaNetAttention.__init__` constructs.\n"
    )
    lines.append("## Per-parameter verdict\n")
    lines.append("| GDN param | vLLM class | LinearBase? | GGUF quant handling |")
    lines.append("|---|---|---|---|")
    for name, cls in GDN_MODULE_CLASSES.items():
        is_lb = linearbase_verdict(cls)
        handling = (
            "quantized — picks up `GGUFLinearMethod`"
            if is_lb
            else "dense — high-precision param, dequant-on-load"
        )
        lines.append(f"| `{name}` | `{cls.__name__}` | {'YES' if is_lb else 'no'} | {handling} |")
    lines.append("")
    lines.append(
        "`conv1d` is a `ColumnParallelLinear` (LinearBase) even though it implements the "
        "causal convolution — its weight is reshaped and loaded via a mamba sharded loader; "
        "GGUF stores `ssm_conv1d` typically at F16/F32 so no low-bit quant applies in practice.\n"
    )
    lines.append("## GGUF GDN-block tensor → vLLM param (preliminary; finalised in T-6)\n")
    lines.append("| GGUF tensor(s) | vLLM param |")
    lines.append("|---|---|")
    for g, v in GGUF_CORRESPONDENCE.items():
        lines.append(f"| `{g}` | {v} |")
    lines.append("")
    lines.append(
        "The GGUF splits the GDN input projection across `attn_qkv` + `attn_gate` "
        "(→ `in_proj_qkvz`) and `ssm_alpha` + `ssm_beta` (→ `in_proj_ba`), while vLLM merges "
        "each pair into one `MergedColumnParallelLinear`. Reconciling this split→merged layout "
        "is the T-6 tensor-map task.\n"
    )
    if config_meta is not None:
        arch = config_meta.get("general.architecture", "?")
        lines.append(f"## Config context\n\nDerived from a `{arch}` metadata fixture: ")
        prefix = arch + "."
        dims = {
            "linear_num_key_heads": config_meta.get(f"{prefix}ssm.group_count"),
            "linear_num_value_heads (inner/state)": (
                (config_meta.get(f"{prefix}ssm.inner_size") or 0)
                // (config_meta.get(f"{prefix}ssm.state_size") or 1)
            ),
            "linear_key/value_head_dim (state_size)": config_meta.get(f"{prefix}ssm.state_size"),
            "linear_conv_kernel_dim": config_meta.get(f"{prefix}ssm.conv_kernel"),
        }
        lines.append(", ".join(f"{k}={v}" for k, v in dims.items()) + "\n")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description="Emit Qwen3.5 GDN LinearBase verdicts")
    ap.add_argument("--config", help="path to a GGUF metadata JSON fixture (optional context)")
    ap.add_argument(
        "--out",
        default=str(Path(__file__).resolve().parent.parent / "docs" / "gdn-module-inventory.md"),
    )
    args = ap.parse_args()

    meta = json.loads(Path(args.config).read_text()) if args.config else None
    doc = build_doc(meta)
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(doc)

    # print the verdict summary
    for name, cls in GDN_MODULE_CLASSES.items():
        print(f"{name:14s} {cls.__name__:28s} LinearBase={linearbase_verdict(cls)}")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
